version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=False

    volumes:
      - ./backend:/app/backend
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
      - ./.env:/app/.env

volumes:
  mysql-data:

networks:
  ml-network:
    driver: bridge 